on: [push]

jobs:
  build:
    name: Linter
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Install ESlint
        run: sudo yarn global add eslint
      - name: Run ESlint
        run: eslint . --ext .js,.jsx,.ts,.tsx --fix
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
    