name: 'Deploy ASP.NET Core app to Azure Web App'

on:
  push:
    branches:
      - "skp"

env:
  DOTNET_VERSION: '3.1.404'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and publish
      - name: dotnet build and publish        
        run: |
         echo "run dot nrt" | exit 0;

      # Publish artifact
      - name: Publish artifact
        
        run: |
         echo "run dot nrtddddddddddddddddddddddddddddd" | exit 0;
         
  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build-and-publish
    steps:

      # Download published artifact
      - name: Download artifact
        run: |
         echo "run dot nrtddddddddddddddddddddddddddddd" | exit 0;

      # Deploy to web app
      - name: Deploy to Azure WebApp
        run: |
         echo "run dot nrtddddddddddddddddddddddddddddd" | exit 0;

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:

      # Download published artifact
      - name: Download artifact      
        run: |
         echo "run dot nrtddddddddddddddddddddddddddddd" | exit 0;

      # Deploy to web app
      - name: Deploy to Azure WebApp
        run: |
         echo "run dot nrtddddddddddddddddddddddddddddd" | exit 0;
